### ISSUE TITLE
[SOLVED] Constantly 1800W?

### ISSUE THREAD

**Issue by zeirix** [fvilmos/power_meter_mqtt#3]
Hi,

thank you for the cool project!

I managed it to run it on a WT32-ETH01 Board (using Ethernet), it is sending MQTT packages as expected.
Only the readout is constantly 1800W, no matter what's happening (Hi/Lo) on Pin 18 (According to IO4 on my board).
These would be 2 pulses/second (my counter has a `PULSES_KWH_RES 1`).

Do you know a bug or a process, which could trigger the Interrupt exactly two times a second?

Thank You!

**Comment by zeirix** [comment]
Sorry for the disturbance.
By accident I figured out, that the Pin numbering is according to the numbering on the board (yes, I'm a ESP32 newbie).
Using `#define IN_PIN_PEM 4` solved the issue.
Have a nice day!

**Comment by fvilmos** [comment]
Hello Zeirix, great that is working now!
